
import { Logger } from '../utils/logger.js';
import { ImportScanner } from './importScanner.js';
import { PackageScanner } from './packageScanner.js';

export class RequirementsGenerator {
  constructor(
    private readonly logger: Logger,
    private readonly importScanner: ImportScanner,
    private readonly packageScanner: PackageScanner,
  ) {}

  async generate(workspaceRoot: string): Promise<string> {
    const importResult = await this.importScanner.scanImports(workspaceRoot);
    const installed = (await this.packageScanner.scanWorkspace(workspaceRoot)).packages;
    const installedMap = new Map(installed.map(p => [p.name.toLowerCase(), p.installedVersion]));

    // Map imports to package names
    const packages = new Set<string>();
    for (const mod of importResult.importedModules) {
      const pkg = this.importScanner.mapToPackageName(mod);
      if (pkg) { packages.add(pkg.toLowerCase()); }
    }

    this.logger.info(
      `RequirementsGenerator: ${packages.size} packages found from ${importResult.filesScanned} files`
    );

    const lines: string[] = [
      '# Auto-generated by Python Package Visualizer',
      `# Generated: ${new Date().toISOString().split('T')[0]}`,
      `# Scanned ${importResult.filesScanned} files, found ${packages.size} packages`,
      '',
    ];
    const sorted = [...packages].sort();
    for (const pkg of sorted) {
      const ver = installedMap.get(pkg);
      lines.push(ver ? `${pkg}==${ver}` : pkg);
    }
    return lines.join('\n');
  }

}
