import * as path from 'path';
import { ScannedPackage } from './packageScanner.js';

export class SetupScriptGenerator {
  generateBash(workspaceRoot: string, scanned: ScannedPackage[]): string {
    const projectName = path.basename(workspaceRoot);
    const hasReqFile = scanned.some(p => p.source && p.source.endsWith('requirements.txt'));
    const hasPyproject = scanned.some(p => p.source && p.source.endsWith('pyproject.toml'));

    return `#!/usr/bin/env bash
# Setup script for ${projectName}
# Generated by Python Package Visualizer
set -e

echo "Creating virtual environment..."
python3 -m venv .venv
source .venv/bin/activate

echo "Upgrading pip..."
pip install --upgrade pip

${hasReqFile ? `echo "Installing dependencies from requirements.txt..."
pip install -r requirements.txt
` : hasPyproject ? `echo "Installing project (pyproject.toml)..."
pip install -e .
` : `echo "Installing packages..."
${scanned.map(p => `pip install "${p.name}${p.installedVersion ? `==${p.installedVersion}` : ''}"`).join('\n')}
`}
echo "Setup complete! Activate with: source .venv/bin/activate"
`;
  }

  generatePowershell(workspaceRoot: string, scanned: ScannedPackage[]): string {
    const projectName = path.basename(workspaceRoot);
    const hasReqFile = scanned.some(p => p.source && p.source.endsWith('requirements.txt'));
    const hasPyproject = scanned.some(p => p.source && p.source.endsWith('pyproject.toml'));

    return `# Setup script for ${projectName}
# Generated by Python Package Visualizer
$ErrorActionPreference = "Stop"

Write-Host "Creating virtual environment..."
python -m venv .venv
.\\.venv\\Scripts\\Activate.ps1

Write-Host "Upgrading pip..."
pip install --upgrade pip

${hasReqFile ? `Write-Host "Installing dependencies from requirements.txt..."
pip install -r requirements.txt
` : hasPyproject ? `Write-Host "Installing project (pyproject.toml)..."
pip install -e .
` : `Write-Host "Installing packages..."
${scanned.map(p => `pip install "${p.name}${p.installedVersion ? `==${p.installedVersion}` : ''}"`).join('\n')}
`}
Write-Host "Setup complete! Activate with: .\\.venv\\Scripts\\Activate.ps1"
`;
  }

  generateMarkdown(workspaceRoot: string, scanned: ScannedPackage[]): string {
    const projectName = path.basename(workspaceRoot);
    const hasReqFile = scanned.some(p => p.source && p.source.endsWith('requirements.txt'));
    const hasPyproject = scanned.some(p => p.source && p.source.endsWith('pyproject.toml'));
    
    const installCmd = hasReqFile ? 'pip install -r requirements.txt' 
                     : hasPyproject ? 'pip install -e .' 
                     : scanned.length > 0 ? 'pip install ' + scanned.map(p => `"${p.name}${p.installedVersion ? `==${p.installedVersion}` : ''}"`).join(' ')
                     : 'pip install <your-packages>';

    return `# ${projectName} \u2014 Setup Guide

> Generated by Python Package Visualizer

## Quick Start

### macOS / Linux
\`\`\`bash
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
${installCmd}
\`\`\`

### Windows (PowerShell)
\`\`\`powershell
python -m venv .venv
.\\.venv\\Scripts\\Activate.ps1
pip install --upgrade pip
${installCmd}
\`\`\`

## Dependencies (${scanned.length})

${scanned.map(p => `- \`${p.name}${p.installedVersion ? `==${p.installedVersion}` : ''}\``).join('\n')}
`;
  }
}
