import * as assert from 'assert';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { RequirementsGenerator } from '../../src/modules/requirementsGenerator.js';
import { ImportScanner } from '../../src/modules/importScanner.js';
import { PackageScanner } from '../../src/modules/packageScanner.js';
import { stubLogger } from '../helpers/stubLogger.js';

suite('RequirementsGenerator', () => {
  let tmpDir: string;

  setup(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ppv-reqgen-'));
    fs.writeFileSync(
      path.join(tmpDir, 'app.py'),
      'import requests\nfrom flask import Flask\nimport cv2\n'
    );
    fs.writeFileSync(path.join(tmpDir, 'requirements.txt'), 'requests>=2.0\n');
  });

  teardown(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  test('generates sorted requirements from real import scan', async () => {
    const importScanner = new ImportScanner(stubLogger);
    const packageScanner = new PackageScanner(stubLogger);
    const generator = new RequirementsGenerator(stubLogger, importScanner, packageScanner);

    const output = await generator.generate(tmpDir);

    assert.ok(output.startsWith('# Auto-generated by Python Package Visualizer'));
    assert.ok(output.includes('Scanned 1 files, found 3 packages'));
    assert.ok(output.includes('flask'));
    assert.ok(output.includes('opencv-python'));
    assert.ok(output.includes('requests'));

    const lines = output.split('\n').filter(l => l && !l.startsWith('#'));
    assert.deepStrictEqual(lines, [...lines].sort());
    assert.strictEqual(lines.length, 3);
  });
});
