import * as assert from 'assert';
import { RequirementsGenerator } from '../../src/modules/requirementsGenerator.js';
import { ImportScanner } from '../../src/modules/importScanner.js';
import { PackageScanner } from '../../src/modules/packageScanner.js';

const stubLogger = {
  debug: () => {},
  info: () => {},
  warn: () => {},
  error: () => {},
  show: () => {},
} as unknown as import('../../src/utils/logger.js').Logger;

suite('RequirementsGenerator', () => {
  test('generates sorted requirements with installed versions', async () => {
    const importScanner = {
      scanImports: async () => ({
        importedModules: new Set(['requests', 'flask', 'cv2']),
        filesScanned: 12,
      }),
      mapToPackageName: (mod: string) => {
        if (mod === 'cv2') { return 'opencv-python'; }
        return mod;
      },
    } as unknown as ImportScanner;

    const packageScanner = {
      scanWorkspace: async () => ({
        packages: [
          {
            name: 'requests',
            installedVersion: '2.32.0',
            specifiedVersion: '',
            source: 'requirements.txt',
            extras: [],
            requires: [],
            group: 'main',
            environment: 'main',
          },
          {
            name: 'flask',
            installedVersion: '3.0.0',
            specifiedVersion: '',
            source: 'requirements.txt',
            extras: [],
            requires: [],
            group: 'main',
            environment: 'main',
          },
          {
            name: 'opencv-python',
            installedVersion: '',
            specifiedVersion: '',
            source: 'requirements.txt',
            extras: [],
            requires: [],
            group: 'main',
            environment: 'main',
          },
        ],
      }),
    } as unknown as PackageScanner;

    const generator = new RequirementsGenerator(stubLogger, importScanner, packageScanner);
    const output = await generator.generate('/fake/workspace');

    assert.ok(output.startsWith('# Auto-generated by Python Package Visualizer'));
    assert.ok(output.includes('Scanned 12 files, found 3 packages'));
    assert.ok(output.includes('flask==3.0.0'));
    assert.ok(output.includes('opencv-python\n') || output.includes('opencv-python\r\n'));
    assert.ok(output.includes('requests==2.32.0'));

    const lines = output.split('\n').filter(l => l && !l.startsWith('#'));
    const sorted = [...lines].sort();
    assert.deepStrictEqual(lines, sorted);
  });
});
