import * as assert from 'assert';
import { SetupScriptGenerator } from '../../src/modules/setupScriptGenerator.js';
import type { ScannedPackage } from '../../src/modules/packageScanner.js';

suite('SetupScriptGenerator', () => {
  const generator = new SetupScriptGenerator();
  const workspace = '/projects/my-app';

  const pkg = (
    name: string,
    source: string,
    installedVersion = '1.0.0'
  ): ScannedPackage => ({
    name,
    specifiedVersion: '',
    installedVersion,
    source: source as ScannedPackage['source'],
    extras: [],
    requires: [],
    group: 'main',
    environment: 'main',
  });

  test('bash script uses requirements.txt when present', () => {
    const script = generator.generateBash(workspace, [
      pkg('requests', 'requirements.txt'),
      pkg('flask', 'requirements.txt'),
    ]);
    const lines = script.split('\n');

    assert.strictEqual(lines[0], '#!/usr/bin/env bash');
    assert.ok(script.includes('set -e'));
    assert.ok(script.includes('python3 -m venv .venv'));
    assert.ok(script.includes('source .venv/bin/activate'));
    assert.ok(script.includes('pip install --upgrade pip'));
    assert.ok(script.includes('pip install -r requirements.txt'));
    assert.ok(!script.includes('pip install -e .'));

    const venvIdx = lines.findIndex(l => l.includes('python3 -m venv'));
    const installIdx = lines.findIndex(l => l.includes('pip install -r requirements.txt'));
    assert.ok(venvIdx >= 0 && installIdx > venvIdx);
    assert.ok(script.endsWith('echo "Setup complete! Activate with: source .venv/bin/activate"\n'));
  });

  test('powershell script uses pyproject.toml when no requirements file', () => {
    const script = generator.generatePowershell(workspace, [
      pkg('requests', 'pyproject.toml'),
    ]);
    const lines = script.split(/\r?\n/);

    assert.ok(script.includes('$ErrorActionPreference = "Stop"'));
    assert.ok(script.includes('python -m venv .venv'));
    assert.ok(script.includes('Activate.ps1'));
    assert.ok(script.includes('pip install -e .'));
    assert.ok(!script.includes('pip install -r requirements.txt'));
    assert.ok(lines.some(l => l.includes('Write-Host "Installing project (pyproject.toml)..."')));
  });

  test('markdown lists dependencies and install command', () => {
    const scanned = [
      pkg('requests', 'requirements.txt', '2.32.0'),
      pkg('flask', 'requirements.txt', '3.0.0'),
    ];
    const md = generator.generateMarkdown(workspace, scanned);

    assert.ok(md.startsWith('# my-app'));
    assert.ok(md.includes('pip install -r requirements.txt'));
    assert.ok(md.includes('`requests==2.32.0`'));
    assert.ok(md.includes('`flask==3.0.0`'));
    assert.ok(md.includes('## Dependencies (2)'));
    assert.ok(md.includes('Generated by Python Package Visualizer'));
  });
});
